### PR TITLE
feat: add babeliser, refactor structure

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Adds `Babeliser` from https://github.com/ShaunSHamilton/babeliser

Examples of how Babeliser is used: https://github.com/freeCodeCamp/solana-curriculum/blob/24bd63522580a4ace7b400a6b2aa759bd5c5d389/curriculum/locales/english/learn-how-to-interact-with-on-chain-programs.md

---

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
I'm not sure, exactly. What's the intention with this PR? Also, snowpack is no-longer maintained.

**Comment by ShaunSHamilton** [comment]
> What's the intention with this PR?

Just to make `Babeliser` available to the helpers.

I cannot remember why we landed on snowpack, but you can see in the ignore files many others were tried.

**Comment by ojeytonwilliams** [comment]
Okay, so I don't entirely get what's going on with the peer dependencies. Are `@babel/generator` and `@babel/parser` already bundled into `babeliser`? If so, that adds a lot to the frame-runner.

**Comment by ShaunSHamilton** [comment]
> Are @babel/generator and @babel/parser already bundled into babeliser?

No. That is why we need the peers.

**Comment by ojeytonwilliams** [comment]
> No. That is why we need the peers.

How are they going to make their way into the client if they're not bundled? Is the plan to update our webpack stuff? Sorry if we've already discussed this.

**Comment by ShaunSHamilton** [comment]
> How are they going to make their way into the client if they're not bundled?

Maybe I misunderstood your earlier question; `babeliser` has required `peerDeps` of `@babel/...`, because it can. Now, as the consumer, this will need to either bundle `@babel/`, or the consumer of this needs to have `@babel/`.

I am not sure which is "nicer". I suppose it could get confusing having 2-3 nests of the same peer deps. Do you have an idea for which direction to go.

The only other thing I can think is that this should be dynamic (tree-shakeable). So, it really does not matter 🤷‍♂️

**Comment by ojeytonwilliams** [comment]
Nah, it's me. I'm a little hazy on exactly how peer deps and bundling interact. Specifically: if we publish as is, will our bundler (webpack) automagically include both this, `babeliser` and the `@/babel` peer deps? Presumably the answer is 'yes', but I'll have to test it to reassure myself.

**Comment by ShaunSHamilton** [comment]
Would this break anything on mobile, @Sembauke ?

**Comment by ShaunSHamilton** [comment]
If `mobile` cannot have peer deps, then this will require more tweaking again to get the dependencies to bundle with the build

**Comment by ShaunSHamilton** [comment]
How do we feel about a `668KB` package?

**Comment by Nirajn2311** [comment]
The compiled code in this PR doesn't work with the mobile app as that code is not compiled for the web ie. there are `process.env` code present and node.js modules(I came across only Buffer as of now) being used. Maybe we can create compile the code into 2 separate files, one for node.js apps and another for the web.

I'll add the steps on how to check if the compiled code works in the mobile app here in some time.

**Comment by ShaunSHamilton** [comment]
I am closing this, as I have tried all build tools I could find, and this does not work for both Nodejs and browser use.

**Pull request closed without merging**
