### PR TITLE
chore(docs): add documentation

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
This adds boilerplate documentation which is deployed at https://opensource.freecodecamp.org/curriculum-helpers/

I will open issues for some other things relating to the docs.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Two thoughts:

- The docs framework used seems like massive overkill (that's a lot of files for documentation)
- Wouldn't we prefer these in the main docs anyway?

**Comment by ShaunSHamilton** [comment]
> Two thoughts:
> 
> * The docs framework used seems like massive overkill (that's a lot of files for documentation)
> * Wouldn't we prefer these in the main docs anyway?

Same answer for both: These are going to be quite extensive docs - lots to say/share.

If we put these in the main docs, I **will** forget to update them, and, if we want the same features, it will take extensive rewrite of the main docs.

**Comment by naomi-lgbt** [comment]
Gonna pull this down and give it a peek tomorrow :3

**Review by naomi-lgbt — APPROVED** [review]
It builds locally and looks like a site.

**Pull request merged**
