### PR TITLE
feat: add helper for matching function strings

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

TODO

- [x] Docs
- [x] Return RegExp instead of string (it's trivial to combine them with other regexes)
- [x] Test against fcc curriculum

The docs should explain this pretty well, but the gist is: this function provides a regex to match function expressions/declarations and arrow functions.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Can we add an option to not look for the closing bracket?

That is, I would want to be able to test:

```js
const naomi = (love) => {
  return love ** 2
}
```

With something like

```js
const regex = new RexExp(`${__helpers.functionRegex("naomi", ["love"])}\s*return\s*love\s*\*\*\s*2)
```

**Comment by ojeytonwilliams** [comment]
Sure! Just to check, do you want something that matches everything up to and including the opening bracket (if there is one)?

e.g.

```js
let codeOne = `const naomi = (love) => {
  return love ** 2
}`
let codeTwo = `function naomi(love) {
  return love ** 3
}`
let trickyArrowCode = `const naomi = love => love**2`

let startRE = functionRegex("naomi", ["love"], { closed: false });

startRE.test(codeOne); // true
startRE.test(codeTwo): // true

let fullRE = new RegExp(startRE.source + /\s*return\s*love\s*\*\*\s*2}/.source)

fullRE.test(codeOne); // true
fullRE.test(codeTwo); // false

let weirdRE = new RegExp(startRE.source + /\s*return\s*love/.source)

weirdRE.test(codeOne); // true
weirdRE.test(codeTwo); // true

let arrowRE = new RegExp(startRE.source + /\s*love\*\*2/.source)
arrowRE.test(trickyArrowCode); // true
```

**Comment by naomi-lgbt** [comment]
Yes that looks great! Thanks!

**Comment by ojeytonwilliams** [comment]
Hey @naomi-lgbt I think it's worked as intended now. There's still the ugly case where it captures too much (described in the docs), but I can't think of a way around that just using regexes. At least not in the time I allocated myself for this!

It should work well enough for our uses and tide us over until we can incorporate the ast-based tooling Shaun created.

**Review by naomi-lgbt — APPROVED** [review]
This should be fine as is

**Pull request merged**
